version: "3"
services:
  rtmp:
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935"
      - "8787:8787"
    env_file:
      - ../.env.rtmp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template
