version: "3"
services:
  rtmp:
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935"
      - "8787:8787"
    env_file:
      - ../.env.rtmp
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - type: bind
        source: ../rtmp/nginx/nginx.conf
        target: /etc/nginx/nginx.conf.template
