version: "3"
services:
  backend:
    # since i'm only going to use this for production deployment, i'm using the gh packages image here.
    image: ghcr.io/sazzo/sazztv-backend:latest
    ports:
      - "1323:1323"
    restart: unless-stopped
    env_file:
      - ../.env.backend
    depends_on:
      - postgres
  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_MULTIPLE_DATABASES: "sazztv"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
